name: Link and make
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main

jobs:
  preset:
    runs-on: ubuntu-latest
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: jq
  linked-markdown:
    runs-on: ubuntu-latest
    needs: preset
    steps:
      - uses: actions/checkout@v3
      - run: ./linker.sh > mindustry-learn-logic.md
      - uses: actions/upload-artifact@v4
        with:
          name: mindustry-learn-logic.md
          path: mindustry-learn-logic.md
