name: Link and make
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main

jobs:
  preset:
    runs-on: ubuntu-latest
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: jq wget
  linked-markdown:
    runs-on: ubuntu-latest
    needs: preset
    steps:
      - uses: actions/checkout@v3
      - run: ./linker.sh > learn-mindustry-logic.md
      - uses: actions/upload-artifact@v4
        with:
          name: learn-mindustry-logic.md
          path: learn-mindustry-logic.md
      - run: |
          hash date tar || exit
          name=learn-mindustry-logic-$(date +%F-%H%M%S).md
          html=${name%.md}.html
          cp -v learn-mindustry-logic.md $name
          wget -O md2html.tar.gz https://github.com/A4-Tacks/markdown2html-converter/releases/download/v2.0.0-local.2/markdown2html-converter-v2.0.0-local.2-x86_64-unknown-linux-musl.tar.gz
          tar -xf md2html.tar.gz
          ./markdown2html-converter --header-ids "" $name -o $html -t learn-mindustry-logic
          mkdir build
          cp $html build/
      - uses: actions/upload-artifact@v4
        with:
          name: learn-mindustry-logic.html
          path: build
